#共用
SuccessFullOperation="successfull operation"
FailFullOperation="failfull operation"
QuerySuccess="query success"
SystemError="system error"
FailGenerateRandomCode="Failed to generate random code Procedure"
FailGenerateCaptchaCode="Failed to generate captcha code"
CaptchaCodeError="Verification code error"
#系统配置
SysConfigInfoDoesNotExists="The configuration info does not exist"
SysConfigNameAlreadyExists="The configuration name already exists"
SysConfigNameDoesNotExists="The configuration name does not exist"
SysConfigAppKeyAlreadyExists="The configuration app_key already exists"
SysConfigAppKeyDoesNotExists="The configuration app_key does not exist"
SysConfigKeyNotEmpty="The configuration key cannot be empty"
#用户
SysUserInfoDoesNotExists="The user information does not exist"
SysUserAccountNameAlreadyExists="The user account name already exists"
SysUserAccountNameDoesNotExists="The user account name does not exist"
SysUserNameAlreadyExists="The user name already exists"
SysUserNameDoesNotExists="The user name does not exist"
SysUserMobileAlreadyExists="The user mobile already exists"
SysUserMobileDoesNotExists="The user mobile does not exist"
SysUserPassWordError="User password error"
SysUserAccountIsDisabled="The user account is disabled"
SysRoleIsInUseByUser="This role:%s is in use by user, please delete it before operating"
#部门
SysDepartmentInfoDoesNotExists="Department information does not exist"
SysDepartmentToParentClassDoesNotExists="The department information of the parent class does not exist"
SysDepartmentNameAlreadyExists="The department name already exists"
SysDepartmentNameDoesNotExists="The department name does not exist"
SysDepartmentIsInUseByUser="The department:%s is in use by user. Please delete it before performing operations"
SysDepartmentIsInUseBySubClasses="The department:%s is in use by subclasses. Please delete it before performing operations"
#岗位
SysPostInfoDoesNotExists="The post information does not exist"
SysPostNameAlreadyExists="The post name already exists"
SysPostNameDoesNotExists="The post name does not exist"
SysPostIsInUseByUser="This post:%s is in use by user, please delete it before operating"
#职级
SysRankInfoDoesNotExists="Rank information does not exist"
SysRankNameAlreadyExists="The rank name already exists"
SysRankNameDoesNotExists="The rank name does not exist"
SysRankIsInUse="This rank:%s is in use by user, please delete it before operating"
#字典
SysDictionaryInfoDoesNotExists="The dictionary information does not exist"
SysDictionaryNameAlreadyExists="The dictionary name already exists"
SysDictionaryNameDoesNotExists="The dictionary name does not exist"
SysDictionaryCodeAlreadyExists="The dictionary code already exists"
SysDictionaryCodeDoesNotExists="The dictionary code does not exist"
#页面元素
SysElementInfoDoesNotExists="The element information does not exist"
SysElementCodeAlreadyExists="The element name already exists"
SysElementCodeDoesNotExists="The element name does not exist"
#用户组
SysGroupInfoDoesNotExists="Group information does not exist"
SysGroupInfoOfTheParentClassDoesNotExists="The group information of the parent class does not exist"
SysGroupNameAlreadyExists="The group name already exists"
SysGroupNameDoesNotExists="The group name does not exist"
#功能操作
SysOperationInfoDoesNotExists="Operation information does not exist"
SysOperationOfTheParentClassDoesNotExists="The operation information of the parent class does not exist"
SysOperationNameAlreadyExists="The operation name already exists"
SysOperationNameDoesNotExists="The operation name does not exist"
SysOperationCodeAlreadyExists="The operation code already exists"
SysOperationCodeDoesNotExists="The operation code does not exist"
SysOperationIsInUseBySubClasses="This function operation:%s is used by subclasses. Please delete it and operate it again"
#系统权限
SysPermissionInfoDoesNotExists="The permission information does not exist"
SysPermissionNameAlreadyExists="The permission name already exists"
SysPermissionNameDoesNotExists="The permission name does not exist"
SysPermissionCodeAlreadyExists="The permission code already exists"
SysPermissionCodeDoesNotExists="The permission code does not exist"
SysPermissionIsInUsePage="The permission:%s is used by the page. Please delete it before operating"
#菜单
SysMenuInfoDoesNotExists="menu information does not exist"
SysMenuInfoOfTheParentClassDoesNotExists="The menu information of the parent class does not exist"
SysMenuNameAlreadyExists="The menu name already exists"
SysMenuNameDoesNotExists="The menu name does not exist"
SysMenuIsInUseBySubClasses="This meun:%s is in use by subclasses, please delete it before operating"
#页面
SysPageInfoDoesNotExists="page information does not exist"
SysPageNameAlreadyExists="The page name already exists"
SysPageNameDoesNotExists="The page name does not exist"
SysPageIsInUseByMenu="Page:%s is used by menu, please delete it before operation"
#角色
SysRoleInfoDoesNotExists="role information does not exist"
SysRoleNameAlreadyExists="The role name already exists"
SysRoleNameDoesNotExists="The role name does not exist"
SysRoleCodeAlreadyExists="The role code already exists"
SysRoleCodeDoesNotExists="The role name does not exist"
#授权
PleaseLogIn="Please log in"
AuthorizationHasExpired="Authorization has expired"
NotloggedIn="Not logged in"
#管理
TokenInvalidation="Token invalidation"
#数据为空
DeleteDataIsNull="Delete data is null"
#暂无定义
DataIsUndefined="Data is undefined"