#共用
SuccessFullOperation="操作成功"
FailFullOperation="操作失败"
QuerySuccess="查询成功"
SystemError="系统错误"
FailGenerateRandomCode="生成随机码失败"
FailGenerateCaptchaCode="验证码生成失败"
CaptchaCodeError="验证码错误"
#系统配置
SysConfigInfoDoesNotExists="配置信息不存在"
SysConfigNameAlreadyExists="配置名称已存在"
SysConfigNameDoesNotExists="配置名称不存在"
SysConfigAppKeyAlreadyExists="配置标识已存在"
SysConfigAppKeyDoesNotExists="配置标识不存在"
SysConfigKeyNotEmpty="配置key为空"
#系统用户
SysUserInfoDoesNotExists="用户信息不存在"
SysUserAccountNameAlreadyExists="账号名称已存在"
SysUserAccountNameDoesNotExists="账号名称不存在"
SysUserNameAlreadyExists="用户姓名已存在"
SysUserNameDoesNotExists="用户姓名不存在"
SysUserMobileAlreadyExists="用户手机号码已存在"
SysUserMobileDoesNotExists="用户手机号码不存在"
SysUserPassWordError="用户密码错误"
SysUserAccountIsDisabled="用户被禁用"
SysRoleIsInUseByUser="该角色:%s被用户使用，请删除后，再操作"
#系统部门
SysDepartmentInfoDoesNotExists="部门信息不存在"
SysDepartmentToParentClassDoesNotExists="父类的部门信息不存在"
SysDepartmentNameAlreadyExists="部门名称已存在"
SysDepartmentNameDoesNotExists="部门名称不存在"
SysDepartmentIsInUseByUser="该部门:%s被用户使用，请删除后，再操作"
SysDepartmentIsInUseBySubClasses="该部门:%s被子类使用，请删除后，再操作"
#系统岗位
SysPostInfoDoesNotExists="岗位信息不存在"
SysPostNameAlreadyExists="岗位名称已存在"
SysPostNameDoesNotExists="岗位名称不存在"
SysPostIsInUseByUser="该岗位:%s被用户使用，请删除后，再操作"
#系统职级
SysRankInfoDoesNotExists="职级信息不存在"
SysRankNameAlreadyExists="职级名称已存在"
SysRankNameDoesNotExists="职级名称不存在"
SysRankIsInUseByUser="该职级:%s被用户使用，请删除后，再操作"
#系统字典
SysDictionaryInfoDoesNotExists="字典信息不存在"
SysDictionaryNameAlreadyExists="字典名称已存在"
SysDictionaryNameDoesNotExists="字典名称不存在"
SysDictionaryCodeAlreadyExists="字典标识已存在"
SysDictionaryCodeDoesNotExists="字典标识不存在"
#系统页面元素
SysElementInfoDoesNotExists="页面元素信息不存在"
SysElementCodeAlreadyExists="页面元素标识已存在"
SysElementCodeDoesNotExists="页面元素标识不存在"
#系统用户组
SysGroupInfoDoesNotExists="用户组信息不存在"
SysGroupInfoOfTheParentClassDoesNotExists="父类的用户组信息不存在"
SysGroupNameAlreadyExists="用户组名称已存在"
SysGroupNameDoesNotExists="用户组名称不存在"
SysGroupIsInUseBySubClasses="该用户组:%s被子类使用，请删除后，再操作"
#系统功能操作
SysOperationInfoDoesNotExists="功能操作信息不存在"
SysOperationOfTheParentClassDoesNotExists="父类的功能操作信息不存在"
SysOperationNameAlreadyExists="功能操作名称已存在"
SysOperationNameDoesNotExists="功能操作名称不存在"
SysOperationCodeAlreadyExists="功能操作标识已存在"
SysOperationCodeDoesNotExists="功能操作标识不存在"
SysOperationIsInUseBySubClasses="该功能:%s操作被子类使用，请删除后，再操作"
#系统文件
SysFileInfoDoesNotExists="文件信息不存在"
SysFileNameAlreadyExists="文件名称已存在"
SysFileNameDoesNotExists="文件名称不存在"
#系统权限
SysPermissionInfoDoesNotExists="权限信息不存在"
SysPermissionNameAlreadyExists="权限名称已存在"
SysPermissionNameDoesNotExists="权限名称不存在"
SysPermissionCodeAlreadyExists="权限标识已存在"
SysPermissionCodeDoesNotExists="权限标识不存在"
SysPermissionIsInUsePage="权限被页面使用，请删除后，再操作"
#菜单
SysMenuInfoDoesNotExists="菜单信息不存在"
SysMenuInfoOfTheParentClassDoesNotExists="父类的菜单信息不存在"
SysMenuNameAlreadyExists="菜单名称已存在"
SysMenuNameDoesNotExists="菜单名称不存在"
SysMenuIsInUseBySubClasses="该菜单:%s被父类使用，请删除后，再操作"
#页面
SysPageInfoDoesNotExists="页面信息不存在"
SysPageNameAlreadyExists="页面名称已存在"
SysPageNameDoesNotExists="页面名称不存在"
SysPageIsInUseByMenu="页面:%s被菜单使用，请删除后，再操作"
#角色
SysRoleInfoDoesNotExists="角色信息不存在"
SysRoleNameAlreadyExists="角色名称已存在"
SysRoleNameDoesNotExists="角色名称不存在"
SysRoleCodeAlreadyExists="角色标识已存在"
SysRoleCodeDoesNotExists="角色标识不存在"
#授权
PleaseLogIn="请登录"
AuthorizationHasExpired="授权已过期"
NotloggedIn="未登录"
#管理
TokenInvalidation="token失效"
#数据为空
DeleteDataIsNull="删除的数据为空"
#暂无定义
DataIsUndefined="暂无定义"
